apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: zero-trust-workload-identity-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: spire-server-serving-cert
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire
    app.kubernetes.io/managed-by: "zero-trust-workload-identity-manager"
    app.kubernetes.io/part-of: "zero-trust-workload-identity-manager"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 443
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9402
      targetPort: 9402
    - name: federation
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire
