//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcmeConfig) DeepCopyInto(out *AcmeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcmeConfig.
func (in *AcmeConfig) DeepCopy() *AcmeConfig {
	if in == nil {
		return nil
	}
	out := new(AcmeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleEndpointConfig) DeepCopyInto(out *BundleEndpointConfig) {
	*out = *in
	if in.HttpsWeb != nil {
		in, out := &in.HttpsWeb, &out.HttpsWeb
		*out = new(HttpsWebConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleEndpointConfig.
func (in *BundleEndpointConfig) DeepCopy() *BundleEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(BundleEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CASubject) DeepCopyInto(out *CASubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CASubject.
func (in *CASubject) DeepCopy() *CASubject {
	if in == nil {
		return nil
	}
	out := new(CASubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfig) DeepCopyInto(out *CommonConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]*corev1.Toleration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1.Toleration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfig.
func (in *CommonConfig) DeepCopy() *CommonConfig {
	if in == nil {
		return nil
	}
	out := new(CommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalStatus) DeepCopyInto(out *ConditionalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalStatus.
func (in *ConditionalStatus) DeepCopy() *ConditionalStatus {
	if in == nil {
		return nil
	}
	out := new(ConditionalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStore) DeepCopyInto(out *DataStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStore.
func (in *DataStore) DeepCopy() *DataStore {
	if in == nil {
		return nil
	}
	out := new(DataStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederatesWithConfig) DeepCopyInto(out *FederatesWithConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederatesWithConfig.
func (in *FederatesWithConfig) DeepCopy() *FederatesWithConfig {
	if in == nil {
		return nil
	}
	out := new(FederatesWithConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationConfig) DeepCopyInto(out *FederationConfig) {
	*out = *in
	in.BundleEndpoint.DeepCopyInto(&out.BundleEndpoint)
	if in.FederatesWith != nil {
		in, out := &in.FederatesWith, &out.FederatesWith
		*out = make([]FederatesWithConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationConfig.
func (in *FederationConfig) DeepCopy() *FederationConfig {
	if in == nil {
		return nil
	}
	out := new(FederationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpsWebConfig) DeepCopyInto(out *HttpsWebConfig) {
	*out = *in
	if in.Acme != nil {
		in, out := &in.Acme, &out.Acme
		*out = new(AcmeConfig)
		**out = **in
	}
	if in.ServingCert != nil {
		in, out := &in.ServingCert, &out.ServingCert
		*out = new(ServingCertConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpsWebConfig.
func (in *HttpsWebConfig) DeepCopy() *HttpsWebConfig {
	if in == nil {
		return nil
	}
	out := new(HttpsWebConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManager) DeepCopyInto(out *KeyManager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManager.
func (in *KeyManager) DeepCopy() *KeyManager {
	if in == nil {
		return nil
	}
	out := new(KeyManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestor) DeepCopyInto(out *NodeAttestor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestor.
func (in *NodeAttestor) DeepCopy() *NodeAttestor {
	if in == nil {
		return nil
	}
	out := new(NodeAttestor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandStatus) DeepCopyInto(out *OperandStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandStatus.
func (in *OperandStatus) DeepCopy() *OperandStatus {
	if in == nil {
		return nil
	}
	out := new(OperandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingCertConfig) DeepCopyInto(out *ServingCertConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingCertConfig.
func (in *ServingCertConfig) DeepCopy() *ServingCertConfig {
	if in == nil {
		return nil
	}
	out := new(ServingCertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriver) DeepCopyInto(out *SpiffeCSIDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriver.
func (in *SpiffeCSIDriver) DeepCopy() *SpiffeCSIDriver {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpiffeCSIDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverList) DeepCopyInto(out *SpiffeCSIDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpiffeCSIDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverList.
func (in *SpiffeCSIDriverList) DeepCopy() *SpiffeCSIDriverList {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpiffeCSIDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverSpec) DeepCopyInto(out *SpiffeCSIDriverSpec) {
	*out = *in
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverSpec.
func (in *SpiffeCSIDriverSpec) DeepCopy() *SpiffeCSIDriverSpec {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverStatus) DeepCopyInto(out *SpiffeCSIDriverStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverStatus.
func (in *SpiffeCSIDriverStatus) DeepCopy() *SpiffeCSIDriverStatus {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgent) DeepCopyInto(out *SpireAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgent.
func (in *SpireAgent) DeepCopy() *SpireAgent {
	if in == nil {
		return nil
	}
	out := new(SpireAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentList) DeepCopyInto(out *SpireAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentList.
func (in *SpireAgentList) DeepCopy() *SpireAgentList {
	if in == nil {
		return nil
	}
	out := new(SpireAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentSpec) DeepCopyInto(out *SpireAgentSpec) {
	*out = *in
	if in.NodeAttestor != nil {
		in, out := &in.NodeAttestor, &out.NodeAttestor
		*out = new(NodeAttestor)
		**out = **in
	}
	if in.WorkloadAttestors != nil {
		in, out := &in.WorkloadAttestors, &out.WorkloadAttestors
		*out = new(WorkloadAttestors)
		(*in).DeepCopyInto(*out)
	}
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentSpec.
func (in *SpireAgentSpec) DeepCopy() *SpireAgentSpec {
	if in == nil {
		return nil
	}
	out := new(SpireAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentStatus) DeepCopyInto(out *SpireAgentStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentStatus.
func (in *SpireAgentStatus) DeepCopy() *SpireAgentStatus {
	if in == nil {
		return nil
	}
	out := new(SpireAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProvider) DeepCopyInto(out *SpireOIDCDiscoveryProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProvider.
func (in *SpireOIDCDiscoveryProvider) DeepCopy() *SpireOIDCDiscoveryProvider {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireOIDCDiscoveryProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderList) DeepCopyInto(out *SpireOIDCDiscoveryProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireOIDCDiscoveryProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderList.
func (in *SpireOIDCDiscoveryProviderList) DeepCopy() *SpireOIDCDiscoveryProviderList {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireOIDCDiscoveryProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderSpec) DeepCopyInto(out *SpireOIDCDiscoveryProviderSpec) {
	*out = *in
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderSpec.
func (in *SpireOIDCDiscoveryProviderSpec) DeepCopy() *SpireOIDCDiscoveryProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderStatus) DeepCopyInto(out *SpireOIDCDiscoveryProviderStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderStatus.
func (in *SpireOIDCDiscoveryProviderStatus) DeepCopy() *SpireOIDCDiscoveryProviderStatus {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServer) DeepCopyInto(out *SpireServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServer.
func (in *SpireServer) DeepCopy() *SpireServer {
	if in == nil {
		return nil
	}
	out := new(SpireServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerList) DeepCopyInto(out *SpireServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerList.
func (in *SpireServerList) DeepCopy() *SpireServerList {
	if in == nil {
		return nil
	}
	out := new(SpireServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerSpec) DeepCopyInto(out *SpireServerSpec) {
	*out = *in
	out.CAValidity = in.CAValidity
	out.DefaultX509Validity = in.DefaultX509Validity
	out.DefaultJWTValidity = in.DefaultJWTValidity
	if in.KeyManager != nil {
		in, out := &in.KeyManager, &out.KeyManager
		*out = new(KeyManager)
		**out = **in
	}
	out.CASubject = in.CASubject
	out.Persistence = in.Persistence
	out.Datastore = in.Datastore
	if in.Federation != nil {
		in, out := &in.Federation, &out.Federation
		*out = new(FederationConfig)
		(*in).DeepCopyInto(*out)
	}
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerSpec.
func (in *SpireServerSpec) DeepCopy() *SpireServerSpec {
	if in == nil {
		return nil
	}
	out := new(SpireServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerStatus) DeepCopyInto(out *SpireServerStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerStatus.
func (in *SpireServerStatus) DeepCopy() *SpireServerStatus {
	if in == nil {
		return nil
	}
	out := new(SpireServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttestors) DeepCopyInto(out *WorkloadAttestors) {
	*out = *in
	if in.WorkloadAttestorsVerification != nil {
		in, out := &in.WorkloadAttestorsVerification, &out.WorkloadAttestorsVerification
		*out = new(WorkloadAttestorsVerification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttestors.
func (in *WorkloadAttestors) DeepCopy() *WorkloadAttestors {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttestors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttestorsVerification) DeepCopyInto(out *WorkloadAttestorsVerification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttestorsVerification.
func (in *WorkloadAttestorsVerification) DeepCopy() *WorkloadAttestorsVerification {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttestorsVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopyInto(out *ZeroTrustWorkloadIdentityManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManager.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopy() *ZeroTrustWorkloadIdentityManager {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeroTrustWorkloadIdentityManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerList.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopy() *ZeroTrustWorkloadIdentityManagerList {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerSpec) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerSpec.
func (in *ZeroTrustWorkloadIdentityManagerSpec) DeepCopy() *ZeroTrustWorkloadIdentityManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerStatus) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]OperandStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerStatus.
func (in *ZeroTrustWorkloadIdentityManagerStatus) DeepCopy() *ZeroTrustWorkloadIdentityManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerStatus)
	in.DeepCopyInto(out)
	return out
}
